name: 🧪Pipeline SanityTest
run-name: ${{github.actor}}👨🏻‍🔬 triggered SanityTest in ${{github.ref_name}}

on:
  push:
    branches: ['GX3-3077-Trello-API-Stcikers'] #! Cambia "TuBranchAqui" por el nombre de tu rama de tarea.
  workflow_dispatch:


jobs:
  SanityTest:
    runs-on: ubuntu-latest

    steps:
    - name: 💻Checkout
      uses: actions/checkout@v4

    - name: 💿Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 🍙 Bun Setup
      uses: oven-sh/setup-bun@v1

    - name: 🧬Install All Dependencies
      run: |
        bun install

    - name: 🧪Cypress Run Test Coverage
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        command: | #todo: EDITAR AQUÍ EL ARCHIVO SUITE A EJECUTAR:
          bun run test:chrome cypress/e2e/Tests/Cards/GX3-3077-TrelloAPI-Stickers.cy.ts

    - name: 📬Generate JUnit/Mocha Report
      if: always()
      run: |
        bun run chrome:report

    - name: ✅Check if XRAY_CLIENT is Defined
      if: always()
      run: |
        if [[ -z "${{ secrets.XRAY_CLIENT_ID }}" ]]; then
          echo "XRAY_CLIENT_ID is not set. Please set it in the repository secrets to enable Slack notifications."
        fi
        if [[ -z "${{ secrets.XRAY_CLIENT_SECRET }}" ]]; then
          echo "XRAY_CLIENT_SECRET is not set. Please set it in the repository secrets to enable Slack notifications."
        fi

    - name: ✅Import Test Results to Xray
      if: env.XRAY_CLIENT != '' && env.XRAY_SECRET != ''
      uses: mikepenz/xray-action@v3
      with: #OPCIONES PARA IMPORTAR LOS RESULTADOS DE PRUEBA A JIRA XRAY:
        username: ${{secrets.XRAY_CLIENT_ID}}
        password: ${{secrets.XRAY_CLIENT_SECRET}}
        testFormat: 'junit' #! NO CAMBIAR
        testPaths: 'cypress/tests_results/junit/chrome_regression_report.xml' #! NO CAMBIAR
        testExecKey: 'GX3-3081' #todo: EDITAR AQUÍ EL TEST EXECUTION A IMPORTAR LAS PRUEBAS.
        projectKey: 'GX3' #todo: EDITAR EN CASO DE TRABAJAR CON OTRO PROYECTO.
      env:
        XRAY_CLIENT: ${{ secrets.XRAY_CLIENT_SECRET }}
        XRAY_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}

    - name: 📊Upload Artifact Mochawesome Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sanity-mocha-report
        path: cypress/tests_reports/chrome_mocha_report
        retention-days: 15

    - name: 🔔Check if SLACK_WEBHOOK is Defined
      if: always()
      run: |
        if [[ -z "${{ secrets.SLACK_WEBHOOK }}" ]]; then
          echo "SLACK_WEBHOOK is not set. Please set it in the repository secrets to enable Slack notifications."
        fi

    - name: 🔔Slack Notification of Done
      if: env.SLACK_WEBHOOK != ''
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Ari✨
        SLACK_MESSAGE: ':test_tube: CYPRESS: SanityTest is Done and imported to Jira :rocket:'
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://image.cdn2.seaart.ai/2023-12-06/clo9g0h4msbc73ac2sog/99e1abc36f32945cd4bacf5ee7448e96194545f7_high.webp
